docs/src/index.md
src/SparseConnectivityTracer.jl
src/tracer.jl
test/benchmark.jl
test/runtests.jl

@gdalle, you were sceptical on this topic, but it looks like BitSets improve the performance even further, cutting runtime in half:
```Julia
julia> include("test/benchmark.jl")
[ Info: Benchmarking Brusselator of size 6 with tracer...
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):  27.000 μs …  2.795 ms  ┊ GC (min … max):  0.00% … 98.14%
Time  (median):     28.917 μs              ┊ GC (median):     0.00%
Time  (mean ± σ):   33.634 μs ± 96.856 μs  ┊ GC (mean ± σ):  12.10% ±  4.15%
▂▆██▅▁    ▁▂▁                                             
▁▂▅███████▆▆▇███▇▆▅▃▃▂▂▂▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
27 μs           Histogram: frequency by time        39.4 μs <
Memory estimate: 108.19 KiB, allocs estimate: 1252.
[ Info: Benchmarking Brusselator of size 6 with …
```

Use `BitSet` for Tracer input set

---

src/SparseConnectivityTracer.jl
src/conversion.jl
src/operators.jl
src/overload_tracer.jl
test/order.jl
test/runtests.jl
test/test_differentiability.jl

Automatically classify `1-to-1`, `2-to-1` and `1-to-2` operators based on differentiation order, by comparing with ForwardDiff.
Gives you a nice summary
and precise errors

Order classification

---

README.md
docs/src/api.md
src/SparseConnectivityTracer.jl
src/adtypes.jl
src/conversion.jl
src/operators.jl
src/overload_connectivity.jl
src/overload_hessian.jl
src/overload_jacobian.jl
src/pattern.jl
src/tracers.jl
test/adtypes.jl
test/runtests.jl
test/test_differentiability.jl

Closes #20
CC: @gdalle @Vaibhavdixit02
```Julia
julia> using SparseConnectivityTracer
julia> x = rand(5);
julia> f(x) = x[1] + x[2]*x[3] + 1/x[4]
f (generic function with 1 method)
julia> H = pattern(f, HessianTracer, x)
5×5 SparseArrays.SparseMatrixCSC{Bool, UInt64} with 3 stored entries:
⋅  ⋅  ⋅  ⋅  ⋅
⋅  ⋅  1  ⋅  ⋅
⋅  1  ⋅  ⋅  ⋅
⋅  ⋅  ⋅  1  ⋅
⋅  ⋅  ⋅  ⋅  ⋅
julia> g(x) = f(x) + x[2]^x[5]
g (generic function with 1 method)
julia> H = pattern(g, HessianTracer, x)
5×5 SparseArrays.SparseMatrixCSC{Bool, UInt64} with 7 stored entries:
⋅  ⋅  ⋅  ⋅  ⋅
⋅  1  1  ⋅  1
⋅  1  ⋅  ⋅  ⋅
⋅  ⋅  ⋅  1  ⋅
⋅  1  ⋅  ⋅  1
```

Add `HessianTracer`

---

src/tracers.jl

Closes #35.
Temporary solution, should get replaced by #34.

Use `mergewith` in `additive_merge`

---

README.md
src/adtypes.jl
src/conversion.jl
src/pattern.jl
src/tracers.jl

Remove constraint `S <: AbstractSet{<:Integer}` in case we want to use vectors or other stuff.
Try to document the expectation of the tracer with respect to the "set" type.
See https://discourse.julialang.org/t/best-data-structure-for-fast-unions-of-large-sets-of-integers/113785/

Remove AbstractIndexSet typing

---

src/tracers.jl

Modify `promote_order` and `distributive_merge` to use `reduce`

Get rid of union!

---

src/SparseConnectivityTracer.jl
src/pattern.jl
src/sortedvector.jl
src/tracers.jl
test/benchmark.jl
test/sortedvector.jl

* Couple key-type of `HessianTracer` dict to set-type
* Move sorting kwarg into inner constructor of `SortedVector`
* When merging `HessianTracer`s, make a set out of the keys outside of the inner loop. This should avoid repeated sorting for `union`s with `SortedVector`.

Improve `HessianTracer` performance

---

src/SparseConnectivityTracer.jl
src/conversion.jl
src/pattern.jl
src/settypes/base_sets.jl
src/settypes/duplicatevector.jl
src/settypes/recursiveset.jl
src/settypes/sortedvector.jl
src/tracers.jl
test/first_order.jl
test/references/show/ConnectivityTracer_BitSet.txt
test/references/show/ConnectivityTracer_DuplicateVector{UInt64}.txt
test/references/show/ConnectivityTracer_RecursiveSet{UInt64}.txt
test/references/show/ConnectivityTracer_Set{UInt64}.txt
test/references/show/ConnectivityTracer_SortedVector{UInt64}.txt
test/references/show/HessianTracer_BitSet.txt
test/references/show/HessianTracer_DuplicateVector{UInt64}.txt
test/references/show/HessianTracer_RecursiveSet{UInt64}.txt
test/references/show/HessianTracer_Set{UInt64}.txt
test/references/show/HessianTracer_SortedVector{UInt64}.txt
test/references/show/JacobianTracer_BitSet.txt
test/references/show/JacobianTracer_DuplicateVector{UInt64}.txt
test/references/show/JacobianTracer_RecursiveSet{UInt64}.txt
test/references/show/JacobianTracer_Set{UInt64}.txt
test/references/show/JacobianTracer_SortedVector{UInt64}.txt
test/second_order.jl

Closes #40 by updating tracers to parametric signatures
* `ConnectivityTracer{I,S}`
* `JacobianTracer{I,S}`
* `HessianTracer{I,S,D}`
Where `I` is the index type, `S` is a (pseudo-)set type and `D` is an `AbstractDict{I,S}`.

Refactor tracer types

---

src/adtypes.jl
src/pattern.jl
test/adtypes.jl

Sparse matrices with Int indices

---

docs/src/api.md
src/SparseConnectivityTracer.jl
src/adtypes.jl
src/conversion.jl
src/exceptions.jl
src/operators.jl
src/overload_comparisons.jl
src/overload_connectivity.jl
src/overload_dual.jl
src/overload_gradient.jl
src/overload_hessian.jl
src/pattern.jl
src/tracers.jl
test/classification.jl
test/first_order.jl
test/second_order.jl

Closes #56.
* Add a `Dual` wrapper type keeping track of primal computations
* rename `GlobalGradientTracer` back to `GradientTracer`
* rename `GlobalHessianTracer` back to `HessianTracer`
Still WIP.

Add local tracers

---

src/operators.jl
src/overload_connectivity.jl
src/overload_gradient.jl
src/overload_hessian.jl
test/classification.jl
test/settypes/sortedvector.jl

Changes:
- Replace the lists of symbols with lists of actual objects
- (Not important) Group tests for `SortedVector` so that they don't skew the total number of tests
Benefits:
- No need to extend `SparseConnectivityTracer.iszero_...`, just `iszero_...`
- Hovering on the symbols gives you the docstring, which is very helpful in this file for classification
I suspect this change could also allow us to avoid metaprogramming altogether in the `overloads...` files, but I haven't yet figured out how

Replace operator symbols with operator objects

---

test/classification.jl

This PR replaces the hacky classification tests based on symbols with tests that use the traits defined internally. Essentially, if we declare that a derivative is zero (locally or globally), we check that ForwardDiff agrees. Note that we don't check the other way around, which means we are free to underspecify zeros

Revamp classification tests

---

src/overload_connectivity.jl
src/overload_gradient.jl
src/overload_hessian.jl

The rationale behind this PR is that we will want to add package extensions (for things like SpecialFunctions.jl), overloading functions that do not necessarily belong to `Base`.
The main changes are:
- I put the overloading mechanism into functions, so that these functions might be called in extensions with new operators
- I added a module argument so that the overloading works outside of `Base` too
It also fixes a few bugs, for which I added TODOs in the source code

Put overloading mechanism into functions

---

src/conversion.jl
src/operators.jl
src/overload_connectivity.jl
test/classification.jl

- Revamp `ConnectivityTracer` to follow the blueprint of `GradientTracer`, except that it uses `is_influence` instead of `is_firstder`
- Add a new category of operators whose influence is zero, and distinguish them from those who have an influence but zero derivatives
- Handle `big`, `widen`, `zero`, `one`, `oneunit`, `typemin`, `typemax`, `eps`, `float`, `floatmin`, `floatmax`, `maxintfloat` like normal `1_to_1` operators _when they are applied to numbers_ (not when they are applied to types)
- Add special case for when ForwardDiff cannot compute derivatives (we assume those derivatives are zero)

Add influence classification for ConnectivityTracer

---

docs/src/api.md
src/SparseConnectivityTracer.jl
src/adtypes.jl
test/adtypes.jl
test/first_order.jl
test/flux.jl
test/second_order.jl

Add `TracerLocalSparsityDetector`

---

Project.toml
docs/src/api.md
src/overload_connectivity.jl
src/overload_gradient.jl
src/overload_hessian.jl
src/tracers.jl

Make `AbstractTracer` subtype of `Real` instead of `Number`. Closes #91.
Not sure whether we need to consider this as breaking, since tracer types are considered internals. However, the documentation mentioned tracers subtyping `Number`.

Make `AbstractTracer` subtype of `Real`

---

src/pattern.jl
test/test_connectivity.jl
test/test_gradient.jl
test/test_hessian.jl

Fix #98 by adding the appropriate methods for converting Hessian tracers to a matrix when the output is not a tracer or dual
Add connectivity, gradient and Hessian tests for `f(x) = 0`

Support Hessians on non-tracer outputs

---

src/tracers.jl
test/test_connectivity.jl
test/test_gradient.jl
test/test_hessian.jl

The `primal` of a `Dual` tracer should never be a tracer itself. 
This will lead to a more informative error in #100.

Constrain type of primal value in `Dual`

---

src/conversion.jl
src/overload_connectivity.jl
src/overload_dual.jl
src/overload_gradient.jl
src/overload_hessian.jl
src/pattern.jl
src/tracers.jl
test/test_hessian.jl

Limit Dual to Real primals, replace all Number with Real

---

src/conversion.jl
src/overload_connectivity.jl
src/overload_gradient.jl
src/overload_hessian.jl
src/pattern.jl
src/tracers.jl
test/runtests.jl
test/test_connectivity.jl
test/test_constructors.jl
test/test_gradient.jl
test/test_hessian.jl

Had to remove the `Dual` overload of `Base.float` on types:
`float(T)` returns a type, not a number usable for the primal.

Fix 3-argument similar and add tests on type conversions

---

.github/workflows/Benchmark.yml
benchmark/benchmarks.jl
benchmark/hessian.jl
benchmark/jacobian.jl
src/tracers.jl

- Restructure Jacobian benchmarks to make them more modular
- Add Hessian benchmarks based on the JuMP hessian article (https://www.tandfonline.com/doi/full/10.1080/10556788.2018.1480625)
> This PR renames benchmark groups and changes the nesting, so it cannot be compared with the `main` branch. But that's ok cause I didn't change the `src` folder, so performance stays the same

Restructure benchmarks, add Hessian test cases

---

.github/workflows/CI.yml

To avoid issues like the one fixed in #110.

Measure code coverage of test directory

---

src/overload_connectivity.jl
src/overload_gradient.jl
src/overload_hessian.jl

Some calls to "inner" overloads can be completely removed, which should avoid the allocation of new sets.

Avoid allocating new tracers

---

benchmark/bench_jogger.jl
src/SparseConnectivityTracer.jl
src/interface.jl
src/overloads/connectivity_tracer.jl
src/overloads/gradient_tracer.jl
src/overloads/hessian_tracer.jl
src/overloads/ifelse_global.jl
src/patterns.jl
src/tracers.jl
test/brusselator.jl
test/classification.jl
test/flux.jl
test/nlpmodels.jl
test/runtests.jl
test/test_arrays.jl
test/test_connectivity.jl
test/test_constructors.jl
test/test_gradient.jl
test/test_hessian.jl
test/tracers_definitions.jl

This is the second attempt at #114 after #119 got derailed by unrelated compile time issues.
___
This PR introduces `AbstractPattern`s that represent sparsity patterns:
```
AbstractPattern
├── AbstractVectorPattern: used in GradientTracer, ConnectivityTracer
│   └── IndexSetVectorPattern
└── AbstractHessianPattern: used in HessianTracer
└── IndexSetHessianPattern
```
Over the last dozens of PRs, we've kept refactoring the Tracer type signatures to accommodate new representations for sparse vectors and sparse matrices, most notably:
* moving away from shared first- and second-order information that were dictionaries of sets (#57)
* introducing custom data types, which had to be forced into the `AbstractSet` interface (#50)
* making second-order information more generic (#103)
* potentially …

Introduce sparsity patterns

---

src/overloads/dual.jl
test/test_gradient.jl
test/test_hessian.jl

Address https://github.com/adrhill/SparseConnectivityTracer.jl/issues/145#issuecomment-2271749831 by adding support for `isless` on `TracerLocalSparsityDetector`.

Support `isless`

---

src/overloads/hessian_tracer.jl

Remove prefix `s` since we're not exclusively working with sets anymore (#155).

Rename variables in Hessian tracer code

---

benchmark/bench_jogger.jl
benchmark/nlpmodels.jl

In recent PRs, we've never needed to benchmark the performance of individual set types.
At this point in development, we should focus on benchmarks of our defaults instead. The only exception in this PR are shared Hessian tracers, which don't have a public API yet.

Smaller benchmarks

---

benchmark/hessian.jl
benchmark/jacobian.jl

The randomness had such a big influence on the sparsity patterns that the benchmark outcomes were random.

Remove randomness from benchmarks

---

benchmark/hessian.jl
benchmark/jacobian.jl

Should fix a weird bug in which benchmarkables that are named like tuples disappear from package benchmark comparison tables, as seen in #155.

Rename benchmarks to avoid parsing of tuples

---

src/interface.jl

Default to new `DictHessianPattern` from #155 for Hessian tracing.
With the updated benchmarks from #157, #159, #160 in place, the CI benchmarks will now compare the performance of both the old and new default.

Use `DictHessianPattern` as default tracer pattern

---

src/overloads/dual.jl
test/test_gradient.jl
test/test_hessian.jl

Closes #153.
* fix `isless` by adding additional method on `AbstractFloat`
* update Jacobian and Hessian tests

Fix `isless` and update tests

---

CHANGELOG.md
Project.toml
ext/SparseConnectivityTracerNNlibExt.jl
ext/SparseConnectivityTracerSpecialFunctionsExt.jl
src/operators.jl
src/overloads/gradient_tracer.jl
src/overloads/hessian_tracer.jl
src/overloads/ifelse_global.jl
test/test_gradient.jl
test/test_hessian.jl

Closes #152.
* Add more methods for `round` and `rand`
* Fix Hessians on NNlib activation functions `celu`, `elu`, `selu` and `hardswish`
* Increase code coverage

More methods for `round` and `rand`, fix NNlib

---

src/SparseConnectivityTracer.jl
src/interface.jl
src/overloads/arrays.jl
test/test_arrays.jl

By having `trace_input` create a `Diagonal` matrix of tracers with only the indices from `diagind`, the sparsity of patterns can be increased by a lot on `Diagonal` inputs:
Previously, this would have returned a dense pattern of ones (see #147).

Increase sparsity for `Diagonal` inputs

---

src/overloads/conversion.jl
src/patterns.jl
test/test_constructors.jl
test/test_hessian.jl

Closes #164 by supporting:
* `Int(d::Dual)`
* `Integer(d::Dual)`
* `Float64(d::Dual)`
* `Float32(d::Dual)`
This currently throws an `InexactError` when tracers are not empty. This is analogous to [ForwardDiff's approach](https://github.com/JuliaDiff/ForwardDiff.jl/blob/a286920bb5e401c8dc5d09589c9764d37cf5c6d2/src/dual.jl#L358-L365).
Depending on the outcome of the ongoing discussion in #167, we might want to make this less conservative for `Int(d)` and `Integer(d)` in the future.

Add direct type conversion on `Dual`

---

src/overloads/conversion.jl
test/test_constructors.jl

* `big`, `widen` and `float` now only return the promoted primal type when called on `Dual` 
* reorganize and shorten the code for type conversions

Refactor type conversions

---

docs/src/dev/adding_overloads.md
src/overloads/special_cases.jl

Specify that the operator overloading guide is written for *"`Function`s that take `Real` arguments"*.
This should clear up some confusion that popped up in https://github.com/adrhill/SparseConnectivityTracer.jl/pull/178#issuecomment-2302074699.

Document limitations of operator overloading utils

---

docs/make.jl
docs/src/dev/adding_overloads.md
docs/src/user/api.md
docs/src/user/limitations.md

* reexport ADTypes interface
* fix typos

Minor fixes to documentation

---

docs/src/dev/adding_overloads.md
ext/SparseConnectivityTracerNNlibExt.jl
ext/SparseConnectivityTracerSpecialFunctionsExt.jl
src/overloads/gradient_tracer.jl
src/overloads/hessian_tracer.jl
src/overloads/utils.jl

* renames utilities from `overload_*` to `generate_code_*`
* adds functions `generate_code_X_to_Y` that call both `generate_code_gradient_X_to_Y` and `generate_code_hessian_X_to_Y`
* update package extensions
* update documentation

Update code generation utilities

---

src/adtypes_interface.jl
src/patterns.jl
src/tracers.jl

Closes #189 with copy-pasteable outputs:
```Julia-repl
julia> TracerSparsityDetector()
TracerSparsityDetector()
julia> TracerSparsityDetector(gradient_tracer_type=SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int,Set{Int}}})
TracerSparsityDetector{SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, Set{Int64}}},SparseConnectivityTracer.HessianTracer{SparseConnectivityTracer.DictHessianPattern{Int64, BitSet, Dict{Int64, BitSet}, SparseConnectivityTracer.NotShared}}}()
julia> # Output can be copied and pasted:
julia> TracerSparsityDetector{SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, Set{Int64}}},SparseConnectivityTracer.HessianTracer{SparseConnectivityTra …
```

Shorter printing of default detectors

---

benchmark/hessian.jl
benchmark/jacobian.jl
docs/src/user/global_vs_local.md
docs/src/user/limitations.md
test/brusselator.jl
test/ext/test_LogExpFunctions.jl
test/ext/test_NNlib.jl
test/ext/test_NaNMath.jl
test/ext/test_SpecialFunctions.jl
test/flux.jl
test/test_arrays.jl
test/test_gradient.jl
test/test_hessian.jl

This was previously inconsistent. `detector` is less ambiguous than `method` and matches ADTypes.jl's `*Detector` naming convention.

Refer to `TracerSparsityDetector` as `detector` instead of `method`

---

src/overloads/ifelse_global.jl
src/patterns.jl
test/ext/test_DataInterpolations.jl

* address warnings from latest JET release 
* skip DataInterpolations test on `LinearInterpolations` until https://github.com/SciML/DataInterpolations.jl/pull/335#issuecomment-2386297056 is resolved.

Fix JET and DataInterpolations tests

---

src/overloads/ambiguities.jl
src/overloads/gradient_tracer.jl
src/overloads/hessian_tracer.jl
src/overloads/utils.jl

Fixes an oversight in #197 by separating overloads on arbitrary types from methods defined on tracers only, thus avoiding duplicate overwriting of existing methods.

Avoid overwriting methods when generating 2-to-1 overloads on arbitrary types 

---

Project.toml
ext/SparseConnectivityTracerForwardDiffExt.jl
src/SparseConnectivityTracer.jl
src/overloads/utils.jl
test/ext/test_ForwardDiff.jl
test/linting.jl
test/runtests.jl

With #197, the ForwardDiff extension is now just one line of code:
```julia
eval(SCT.generate_code_2_to_1(:Base, SCT.ops_2_to_1, ForwardDiff.Dual))
```
Closes #196.

Add ForwardDiff package extension

---

Project.toml
src/SparseConnectivityTracer.jl
src/parse_outputs_to_mat.jl
src/parse_outputs_to_matrix.jl
src/trace_functions.jl
test/test_gradient.jl

Relax type annotations in Jacobian output parsing

---

Project.toml

I didn't see a CompatHelper PR, but see the action failed last two times, not sure why: https://github.com/adrhill/SparseConnectivityTracer.jl/actions/workflows/CompatHelper.yml
The breaking changes relate to the extrapolation API, which doesn't affect this package.
https://github.com/SciML/DataInterpolations.jl/releases/tag/v7.0.0

Add compat for DataInterpolations v7

---

Project.toml
src/overloads/arrays.jl
test/test_arrays.jl

Closes #224 by adding overloads for 3-argument `dot`.
The 2-argument version in LinearAlgebra.jl is generic enough to support SCT.

Add overloads for `dot`

---

CHANGELOG.md
Project.toml
docs/src/user/api.md
src/SparseConnectivityTracer.jl
src/adtypes_interface.jl
test/runtests.jl
test/test_buffers.jl

For use in external packages like DI (see https://github.com/JuliaDiff/DifferentiationInterface.jl/issues/737).
I'm open to a name change for the two functions.

Add stable API for allocation of buffers

---

Project.toml
ext/SparseConnectivityTracerDataInterpolationsExt.jl
test/ext/test_DataInterpolations.jl

The breaking change in this release is https://github.com/SciML/DataInterpolations.jl/pull/396.
In that PR SparseConnectivityTracer was mentioned as one of the few users of the output dimension type parameter, and the [`output_dim`](https://github.com/SciML/DataInterpolations.jl/pull/396/files#diff-ec9d52d592efcfac03054654f1ddb93fa39df2988f98c3fd169c7f6c40c0ad1b) function was added to support SCT. In this PR I don't use that yet since it is different from what was used for the type parameter before, [`get_output_dim`](https://github.com/SciML/DataInterpolations.jl/pull/396/files#diff-fa2846ef87a68f71065b886fe1d1957d611d94d3478d183e44a6e6c88dbf6739). So I moved that function into the extension.
This works, though perhaps it would be better to use `output_dim` instead and simplify the code …

DataInterpolations v8 compatiblity

---

docs/src/internals/adding_overloads.md
docs/src/user/limitations.md
src/operators.jl
src/overloads/gradient_tracer.jl
src/overloads/hessian_tracer.jl
test/test_gradient.jl
test/test_hessian.jl

* Make changes in #248 permanent by reverting #247.
* Document design principles, which could use a second pair of eyes (ping @gdalle).

Remove global overloads based on auxiliary values, document design principles
